### ISSUE TITLE
Versão mais atualizada!

### ISSUE THREAD

**Issue by Joao-Victor-Bonfim** [M2Costa/Implicare#3]
Morato, se possível, me manda a versão mais atualizada do projeto?

**Comment by M2Costa** [comment]
Tá no computador da Joice, tô esperando ela me enviar

Matheus Morato da Costa
Centro Federal de Educação Tecnológica de Minas Gerais
Curso Técnico em Informatica
Terceiro Ano

________________________________

**Comment by Joao-Victor-Bonfim** [comment]
Que droga ein!?
